### ISSUE TITLE
Peer Dependency limits to Karma 5

### ISSUE THREAD

**Issue by askrachelle** [monounity/karma-coverage-istanbul-instrumenter#7]
The peerDependency is specifically tied to 3 || 4 || 5 so Karma cannot be updated to 6 for security patches when using this pkg.  This is a great little coverage item.  Can you make this peer dependency more flexible in the package.json?

```
  "peerDependencies": {
    "karma": "3 || 4 || 5"
  }
```

**Comment by Sayan751** [comment]
@erikbarke Any plan to release the new version? Or are you still testing for compatibility?

**Comment by erikbarke** [comment]
1.0.4 is on npm now 🚀
